//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking1
    {
        public string Имя_хозяина { get; set; }
        public string Фамилия_хозяина { get; set; }
        public string Кличка { get; set; }
        public System.DateTime Дата_заселения { get; set; }
        public System.DateTime Дата_выселения { get; set; }
        public int Номер_комнаты { get; set; }
        public int Стоимость_проживания { get; set; }
        public int Долг { get; set; }
        public System.Guid BookingID { get; set; }
    }
}
