//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid PaymentID { get; set; }
        public System.Guid BookingID { get; set; }
        public int Payment1 { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
